name: weather

dependencies:
  - python=3.7.0
  - numpy=1.18.1
  - pandas=1.0.0
  - scipy=1.1.0
  - matplotlib=3.1.3
  - seaborn=0.9.0
  - scikit-learn=0.22.0
  - jupyter
  - ipykernel
  - nb_conda
  - h5py=2.10.0
  - pip:
    - nbdime
    - tables
    - xlrd